# Generated by Django 4.2 on 2023-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
