# Generated by Django 4.2 on 2023-05-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0002_feedback_date_feedback_email_feedback_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_name',
        ),
    ]
