# Generated by Django 4.2 on 2023-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0003_remove_feedback_email_remove_feedback_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='am_10',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='slot',
            name='am_11',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='slot',
            name='pm_2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='slot',
            name='pm_3',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='slot',
            name='pm_4',
            field=models.IntegerField(default=10),
        ),
    ]
