# Generated by Django 4.2 on 2023-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0005_alter_slot_avalible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='avalible',
            field=models.BooleanField(default=True),
        ),
    ]
