# Generated by Django 4.2 on 2023-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0006_alter_slot_avalible'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
