# Generated by Django 4.2 on 2023-05-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0007_chat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rewards_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SMBM_APP.rewards'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
