# Generated by Django 4.2 on 2023-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0008_alter_booking_rewards_id_alter_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rewards_id',
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
