# Generated by Django 4.2.1 on 2023-05-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0009_remove_booking_rewards_id_alter_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rewards_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMBM_APP.rewards'),
        ),
    ]
