# Generated by Django 4.2 on 2023-05-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0010_booking_rewards_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rewards_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMBM_APP.rewards'),
        ),
    ]
