# Generated by Django 4.2 on 2023-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0011_alter_booking_rewards_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
