# Generated by Django 4.2 on 2023-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0012_alter_booking_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
