# Generated by Django 4.2 on 2023-05-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0013_alter_booking_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rewards_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMBM_APP.rewards'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
