# Generated by Django 4.2 on 2023-05-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0014_alter_booking_rewards_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
