# Generated by Django 4.2 on 2023-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMBM_APP', '0017_chat_from_user_chat_tiem_remove_chat_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='tiem',
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
